### ISSUE TITLE
Evaluate and replace Nile commands

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa801#2]
# Overview
We should attempt to replace `nile` with a new set of custom `drush` scripts`.

- `ldu` would go away and be replaced by composer.
- Generate multi-site could replace `lsp`. We would want to allow the site to be hooked up to an external repo.
- `ceb` would go away and be replaced by pipelines cli or gui.
- `csp` could be a custom drush command that executes cloud hooks. Drush 9 uses symfony console.

# Commands
## ~~~cloud:environment-build~~~
~~~Trigger a environment rebuild on Acquia Cloud.~~~

## cloud:generate-saml-config
Generate the SAML config for the docroot.

## cloud:manifest-report
Print reports about sites in the manifest.

## cloud:site-provision
Provision a new multisite in Acquia Cloud.

## ~~~cloud:slack-message~~~
~~~Send a Slack message to the Slack URL environment variable.~~~

## ~~~local:docroot-update~~~
~~~Update Drupal and dependencies.~~~

## ~~~local:site-provision~~~
~~~Generate a single site for Dev Desktop.~~~

## ~~~shared:generate-aliases~~~
~~~Generate Drush aliases from a manifest.~~~

## ~~~shared:generate-sites~~~
~~~Generate sites from a manifest.~~~

**Comment by richardbporter** [comment]
I crossed out what I think won't need to exist for D8.

**Comment by richardbporter** [comment]
I don't think any Nile command will migrate as-is. We can simply use snippets from Nile as needed. Closing this in favor of more specific tasks that I will outline soon.
