### ISSUE TITLE
Manifest + Generator

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa801#3]
Ideally we could provide a sites.yml file for each application. We should look at dynamically generating the xml endpoint as part of the build process.

We should check with the authentication team to see if they can handle multiple endpoints.

**Comment by adamdelaney** [comment]
There could be an issue because we would track each branch separately.

**Comment by richardbporter** [comment]
This should be easier to automate the addition to the manifest and Git commands.

**Comment by richardbporter** [comment]
I think we should go another direction here and move the manifest to the default database. I'll create more specific issues in the https://github.com/uiowa/multisite repo.
